/**
 * 支付错误码定义
 * @description 统一定义所有错误码，便于错误处理和国际化
 */

export const ERROR_CODES = {
  // 网络相关错误 (1000-1099)
  NETWORK_ERROR: 'NETWORK_ERROR_1001',
  REQUEST_TIMEOUT: 'NETWORK_ERROR_1002',
  CONNECTION_FAILED: 'NETWORK_ERROR_1003',
  TIMEOUT_ERROR: 'NETWORK_ERROR_1004', // 新增：超时错误

  // 配置相关错误 (3000-3099)
  CONFIG_ERROR: 'CONFIG_ERROR_3001',
  INVALID_CONFIG: 'CONFIG_ERROR_3002',
  MISSING_CONFIG: 'CONFIG_ERROR_3003',
  CONFIG_LOAD_FAILED: 'CONFIG_ERROR_3004',

  // 业务相关错误 (4000-4099)
  BUSINESS_ERROR: 'BUSINESS_ERROR_4001',
  PAYMENT_FAILED: 'BUSINESS_ERROR_4002',
  REFUND_FAILED: 'BUSINESS_ERROR_4003',
  INVALID_PARAMS: 'BUSINESS_ERROR_4004',

  // 服务相关错误 (5000-5099)
  SERVICE_ERROR: 'SERVICE_ERROR_5001',
  SERVICE_UNAVAILABLE: 'SERVICE_ERROR_5002',
  SERVICE_TIMEOUT: 'SERVICE_ERROR_5003',
  INVALID_SERVICE_TYPE: 'SERVICE_ERROR_5004',

  // 参数相关错误 (6000-6099)
  PARAM_ERROR: 'PARAM_ERROR_6001',
  MISSING_REQUIRED_PARAM: 'PARAM_ERROR_6002',
  INVALID_PARAM_TYPE: 'PARAM_ERROR_6003',
  INVALID_PARAM_VALUE: 'PARAM_ERROR_6004',

  // 权限相关错误 (7000-7099)
  PERMISSION_ERROR: 'PERMISSION_ERROR_7001',
  ACCESS_DENIED: 'PERMISSION_ERROR_7002',
  TOKEN_EXPIRED: 'PERMISSION_ERROR_7003',
  INVALID_TOKEN: 'PERMISSION_ERROR_7004',

  // 系统相关错误 (8000-8099)
  SYSTEM_ERROR: 'SYSTEM_ERROR_8001',
  UNKNOWN_ERROR: 'SYSTEM_ERROR_8002',
  INTERNAL_ERROR: 'SYSTEM_ERROR_8003',
  RESOURCE_NOT_FOUND: 'SYSTEM_ERROR_8004',
}

/**
 * 错误码对应的默认消息
 */
export const ERROR_MESSAGES = {
  [ERROR_CODES.NETWORK_ERROR]: '网络连接失败，请检查网络设置',
  [ERROR_CODES.REQUEST_TIMEOUT]: '请求超时，请稍后重试',
  [ERROR_CODES.CONNECTION_FAILED]: '连接服务器失败',
  [ERROR_CODES.TIMEOUT_ERROR]: '操作超时，请稍后重试',

  [ERROR_CODES.CONFIG_ERROR]: '系统配置错误，请联系管理员',
  [ERROR_CODES.INVALID_CONFIG]: '配置参数无效',
  [ERROR_CODES.MISSING_CONFIG]: '缺少必要配置',
  [ERROR_CODES.CONFIG_LOAD_FAILED]: '配置加载失败',

  [ERROR_CODES.BUSINESS_ERROR]: '业务处理失败',
  [ERROR_CODES.PAYMENT_FAILED]: '支付失败，请重试',
  [ERROR_CODES.REFUND_FAILED]: '退款失败，请联系客服',
  [ERROR_CODES.INVALID_PARAMS]: '参数错误，请检查输入',

  [ERROR_CODES.SERVICE_ERROR]: '服务处理失败',
  [ERROR_CODES.SERVICE_UNAVAILABLE]: '服务暂不可用',
  [ERROR_CODES.SERVICE_TIMEOUT]: '服务响应超时',
  [ERROR_CODES.INVALID_SERVICE_TYPE]: '无效的服务类型',

  [ERROR_CODES.PARAM_ERROR]: '参数错误',
  [ERROR_CODES.MISSING_REQUIRED_PARAM]: '缺少必要参数',
  [ERROR_CODES.INVALID_PARAM_TYPE]: '参数类型错误',
  [ERROR_CODES.INVALID_PARAM_VALUE]: '参数值无效',

  [ERROR_CODES.PERMISSION_ERROR]: '权限错误',
  [ERROR_CODES.ACCESS_DENIED]: '访问被拒绝',
  [ERROR_CODES.TOKEN_EXPIRED]: '令牌已过期',
  [ERROR_CODES.INVALID_TOKEN]: '无效的令牌',

  [ERROR_CODES.SYSTEM_ERROR]: '系统错误',
  [ERROR_CODES.UNKNOWN_ERROR]: '未知错误',
  [ERROR_CODES.INTERNAL_ERROR]: '内部错误',
  [ERROR_CODES.RESOURCE_NOT_FOUND]: '资源未找到',
}

/**
 * 获取错误消息
 * @param {string} errorCode - 错误码
 * @returns {string} 错误消息
 */
export function getErrorMessage(errorCode) {
  return ERROR_MESSAGES[errorCode] || ERROR_MESSAGES[ERROR_CODES.UNKNOWN_ERROR]
}
